# Generated by Django 4.2.2 on 2025-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_customer_added_by_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
    ]
