# Generated by Django 4.2.2 on 2025-05-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_customer_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='added_by',
            field=models.CharField(max_length=150),
        ),
    ]
