# Generated by Django 4.2.2 on 2025-05-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_customer_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
